services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
